### ISSUE TITLE
Publish to Maven Central (or JCenter)

### ISSUE THREAD

**Issue by rm3l** [Yelp/android-varanus#6]
Hi there!

First of all, thanks for this awesome library.
Maybe I've missed something, but I can't find `android-varanus` published anywhere in the public repos. I've looked for it on both Maven Central and JCenter, but could not find it.
The setup instructions say:
```groovy
// Top level build.gradle
allprojects {
	repositories {
		mavenCentral()
	}
}

// Module level build.gradle
dependencies {
    implementation "com.yelp.android:varanus:<version-number>"
}
```

And replacing `<version-number>` with the current version (`2.0.2`) results in the following error message at build time: `ERROR: Failed to resolve: com.yelp.android:varanus:2.0.2`

Am I missing something?

**Comment by redwarp** [comment]
Hey @rm3l , the version 2.0.4 is now available in maven central. Something was wrong with our publishing process previously, but is now fixed.

**Comment by rm3l** [comment]
Great - thanks @redwarp ! I can confirm the library is now downloadable from Maven Central. I can now start playing with it ;)
